### ISSUE TITLE
Request: Add support for binary prefixes (KiB/MiB) in addition to decimal prefixes (KB/MB)

### ISSUE THREAD

**Issue by fragmer** [omar/ByteSize#1]
It would be very useful to add an option to handle both binary prefixes (kibi/mebi/gibi/tebi/pebi) and decimal prefixes (kilo/mega/giga/tera/peta), for parsing and formatting.

**Comment by JasonRitchie** [comment]
Re: 1. Bytes and bits are used in both the decimal and binary space, so keeping the name ByteSize is not inaccurate.

**Comment by omar** [comment]
On a related note, the current library incorrectly or correctly (depending on how you look at it) uses the ratio 1 KB = 1024 bytes. If we were to add `KiBi` we'd need to change the `KB` to use the ratio of 1 KB = 1000 bytes.

This comes to mind https://xkcd.com/394/

**Comment by omar** [comment]
FYI, I started some work on this in 166ccb.

**Comment by omar** [comment]
I decided to make this v2 given the changes that went into. An alpha is up on NuGet https://www.nuget.org/packages/ByteSize/2.0.0-alpha1

**Comment by omar** [comment]
Track progress in #24
