### ISSUE TITLE
Request ByteSize.MinValue 0

### ISSUE THREAD

**Issue by taori** [omar/ByteSize#12]
Hi, i want to propose a change of ByteSize.MinValue.

I've just used the property and expected it to be zero since negative amounts of data are impossible.

I just wanted to mention this, since it would be the value most consumers would probably expect this as MinValue.

OT: Nice work on this library. Much appreciated.

**Comment by omar** [comment]
Thanks Taori. I can't think of a reason to not set `ByteSize.MineValue` to `0`. Do you want to open a PR for this?

**Comment by taori** [comment]
Hi omar. Alright. I'll do one once i get home. Thanks.

**Comment by taori** [comment]
Hi Omar. Are you ready to pull or do you want me to change something?

**Comment by omar** [comment]
Thank you for your contribution. I've packaged this into v1.1.2 and uploaded to NuGet at https://www.nuget.org/packages/ByteSize/1.1.2

**Comment by taori** [comment]
You're welcome and thanks again for the effort you've put into this library
