### ISSUE TITLE
Localization of TryParse function.

### ISSUE THREAD

**Issue by Xor-el** [omar/ByteSize#15]
Hello.
first of all, thanks for providing such wonderful library, it is highly appreciated.
it would be nice if you could localize tryparse  and parse functions or provide an overload that supports localization.
 this line in ByteSize.cs 

if (!( char .IsDigit(s[num]) || s[num] == '.'))

would cause your library to fail when running 

ByteSize.Parse("1,55 GB");

although this is valid in german locale where comma is the official decimal seperator. 

so I guess you could replace the dot with numberformat.NumberDecimalSeparator where numberformat is a NumberFormatInfo variable. 

regards and thanks in anticipation.

**Comment by omar** [comment]
Thanks for the feedback. Would you like to open a PR with the fix so I can review it and publish the update?

**Comment by omar** [comment]
@Xor-el, I've fixed this issue in 0c17c11. The NuGet package has been uploaded and is ready for download (v1.2.0 - https://www.nuget.org/packages/ByteSize/1.2.0).

Thanks for pointing this issue out.

**Comment by Xor-el** [comment]
@Omar, Thanks for the Fix. 
Well done.
