### ISSUE TITLE
ByteSize of zero returns unexpected formatting of " b"

### ISSUE THREAD

**Issue by atifaziz** [omar/ByteSize#21]
```c#
Console.WriteLine(new ByteSize(0).ToString());
Console.WriteLine(ByteSize.FromBytes(0).ToString());
Console.WriteLine(ByteSize.MinValue.ToString());
```

All of the above return (space following by a lowercase B):

```
 b
 b
 b
```

I'm guessing this is not the intended behavior? Certainly isn't desired.

**Comment by omar** [comment]
This is indeed not desired. The output of each of those should be `0 b`.

I'll take a look at this tonight and see if I can patch this. Thanks for pointing this out.

**Comment by atifaziz** [comment]
> I'll take a look at this tonight and see if I can patch this.

If you don't get the chance tonight then let me know and I can send a PR tomorrow if it'd help.

**Comment by omar** [comment]
I just pushed out [v1.2.3 on NuGet](https://www.nuget.org/packages/ByteSize/1.2.3) with this fix. Would like to get your take on the fix though as I'm not too familiar with the best approach to handle custom ToString methods.

**Comment by atifaziz** [comment]
Thanks for the quick turn around on the fix and pushing out a new version! My local fix was exactly the same (i.e. use `0.##` instead of `#.##`) and what I was intending to submit as a PR.

**Comment by omar** [comment]
Happy to help. Glad you're getting value out of this library.
