### ISSUE TITLE
Mebibytes

### ISSUE THREAD

**Issue by MarkSFrancis** [omar/ByteSize#31]
The units being used in this project are actually kibibyte, mebibyte, gibibyte etc instead of kilobyte, megabyte, gigabyte (MiB for mebibyte, MB for megabyte) which may cause confusion. 
Kilobyte is 1000 bytes (power of 10), but a kibibyte is 1024 bytes (power of 2).

More info on what a kibibyte is:
https://en.wikipedia.org/wiki/Kibibyte

**Comment by omar** [comment]
Track progress of this feature here #24

**Comment by omar** [comment]
v2 now supports this, see https://www.nuget.org/packages/ByteSize/2.0.0
