### ISSUE TITLE
Binaries are not strong name signed 

### ISSUE THREAD

**Issue by tomerrt** [omar/ByteSize#33]
Hi,

This is preventing us from calling the byteSize dll from a strong name assembly file (signed code can't call unsigned code). 

Can you please sign your binary?

**Comment by AndreasHassing** [comment]
Just grab the code and add to your project?

**Comment by sebbe33** [comment]
This package not being strong-name signed causes issues for us as well. @omar any chance of getting the binaries strong-named signed and publishing a new version? Should be a fairly easy thing to do https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name :)

Thanks,
// Seb

**Comment by JDA88** [comment]
+1 This is preventing us to use the NuGet package and we have to integrate the sources into our own library as a workaround

**Comment by omar** [comment]
@JDA88, @sebbe33, @tomerrt, I just published v2.1.2 which is strongly named. https://www.nuget.org/packages/ByteSize/2.1.2
