### ISSUE TITLE
Migrate to csproj

### ISSUE THREAD

**Issue by Tyrrrz** [omar/ByteSize#35]
I'm using this library in an app that runs inside a docker container. Due to having been built with project.json format, this library requires an sdk image to run, which is significantly bigger than the runtime image. Switching to csproj should fix it.

**Comment by omar** [comment]
Hey @Tyrrrz, this will be solved in the 2.0 release (see [v2.0.0-alpha](https://www.nuget.org/packages/ByteSize/2.0.0-alpha1)). That version is built for .NET Standard and uses .csproj.

It seems to be pretty stable at the moment and I'm hoping to promote it to stable v2 after I finish reviewing comments on #24.

**Comment by Tyrrrz** [comment]
I'm not really interested in the metric changes in 2.0 and I would like this fix as soon as possible. I can make a PR with just this change, would you merge it?

**Comment by Tyrrrz** [comment]
Also I would need to use this library in a project targeting net45
