### ISSUE TITLE
Code bug

### ISSUE THREAD

**Issue by pgolebiowski** [omar/ByteSize#37]
```csharp
ByteSize.FromBits(Int64.MaxValue);
```

The above initializes the struct with a number of bits equal to `-9223372036854775808`. Surrounding large numbers also don't work.

Please fix your math or change the argument type to `Int32` if you handle smaller numbers only.

**Comment by omar** [comment]
Thanks for pointing this out, I've fixed the issue in this commit that's slated to be part of the next version. https://github.com/omar/ByteSize/pull/24/commits/6425b779a3f4f16fc16465e7376d60081a7f1efd#diff-d2822c0dc3a5209b07ad5954b9c3ddaa

**Comment by omar** [comment]
This fix is in v2, see https://www.nuget.org/packages/ByteSize/2.0.0
