### ISSUE TITLE
Seemingly huge number of dependencies for a "small library"

### ISSUE THREAD

**Issue by fdbeirao** [omar/ByteSize#47]
Hello,

I am trying to use this library, but the moment I do add nuget package (Visual Studio Professional 2019, 16.8.3) I am greeted with this list of "dependencies"/about to install:

![image](https://user-images.githubusercontent.com/6030940/102226228-715a2500-3ee8-11eb-956a-b7ab333b8de1.png)

My csproj for this particular project is actually quite straightforward:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

So I am trying to keep things lean in my codebase, but if I look at that window of changes about to happen to my project, I think twice "Okay, do I really need this library?"

To be honest I would expect zero dependencies from ByteSize.

Or am I missing something obvious?

Kind regards and thanks.

**Comment by GordonFreemanK** [comment]
It doesn't have any _particular_ dependency but there are only a .net standard 1.0 and .net 4.5 builds.
I believe your project being .net 5 it resolves to the .net standard 1.0 build of the lib, and has to pull a huge number of .net core libraries to get it to run.
I think your issue could be rephrased as "please add a .net 5.0 target to the library build", which would probably not be very complicated.

**Comment by julealgon** [comment]
Any updates on this? It is a fairly sensible concern with a potentially very straightforward fix.

**Comment by omar** [comment]
The next release will have this fixed.

**Comment by fdbeirao** [comment]
👍🏻 Awesome work, @omar 

![image](https://user-images.githubusercontent.com/6030940/132076690-3ca21497-14f4-4767-b970-8c1d1d9540f5.png)
