### ISSUE TITLE
Change root namespace to avoid conflict

### ISSUE THREAD

**Issue by omar** [omar/ByteSize#6]
Naming a type in a namespace the same as the namespace is considered [bad practice](http://blogs.msdn.com/b/ericlippert/archive/2010/03/09/do-not-name-a-class-the-same-as-its-namespace-part-one.aspx).

I'd like to change the namespace so as to avoid IDE autocomplete conflicts and to follow best practices. However, I'm not sure what to use:

- `Omar.ByteSize`
- `Bytes.ByteSize`

**Comment by JasonRitchie** [comment]
I agree that this would be a welcome change. ByteSizeLib.ByteSize makes sense.

**Comment by omar** [comment]
Done.
