### ISSUE TITLE
FR: ToString() method that uses the largest metric prefix whose value is greater than or equal to 1, using the binary values instead of decimal values.

### ISSUE THREAD

**Issue by jerrywoo96** [omar/ByteSize#70]
ToString() method that uses the largest metric prefix whose value is greater than or equal to 1, using the binary values instead of decimal values.

Use case: Windows display the binary values, so as to align to windows file sizes for comparison.

**Comment by sandrock** [comment]
I don't understand your request. May you add an example of what you are trying to achieve?

**Comment by omar** [comment]
@jerrywoo96 there's a `.ToBinaryString()` method that should do what you need.
